### ISSUE TITLE
Filtered properties show up in cache

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-DoocsBackend#13]
The history properties (.FILT etc.) should not show up in the RegisterCatalogue. Filtering for these properties was recently added. Those properties now appear in the cache. Maybe the filtering was removed in the process of #6? @vargheseg, can you comment on this?

**Comment by mhier** [comment]
It appears the filtering is just missing some patterns to remove. I will add them.

**Comment by phako** [comment]
This is fixed then I suppose?

**Comment by mhier** [comment]
yes, seems to be fixed
