### ISSUE TITLE
Catalogue cache might get corrupted on unexpected shutdown

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-DoocsBackend#15]
If the application shuts down early (e.g. by an exception in the startup phase), the catalogue cache often is corrupted. It then looks just like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<catalogue version="1.0"/>
```

This prevents applications from starting then properly, because the catalogue is then empty.

**Comment by mhier** [comment]
Seems to work also in the context where I have observed this error frequently. Thanks!

**Comment by mhier** [comment]
It's still happening :-(

**Comment by phako** [comment]
There is one codepath where we potentially save an empty catalog. If the `EqCall::names` call in `CatalogueFetcher::fillCatalogue` fails (because the server is temporarily not available), it will just return with an empty catalogue which will then be saved to disk

**Comment by phako** [comment]
next try. Since I could not reproduce the issue I also cannot test if that was the root cause.
