### ISSUE TITLE
Cache is sometimes written with access_mode of random data instead of "wait_for_new_data"

### ISSUE THREAD

**Issue by phako** [ChimeraTK/DeviceAccess-DoocsBackend#17]
Under some circumstances, the cache is written with an invalid character instead of the text "wait_for_new_data"

**Comment by phako** [comment]
This was a one-off issue. Needs to be reproduced. 

Happened when starting/stopping a server with a minimal cache for a the timer server

**Comment by vargheseg** [comment]
Could not reproduce the issue:
Tests done:
- Tried a minimal working example and ran compiler sanitizers on it; it did not complain.
- Hacked the code path to write an xml with 100+ elements; ran ok.
- Read the code, but I do not  find what could go wrong.
