### ISSUE TITLE
Bug in cache file mechanism

### ISSUE THREAD

**Issue by nshehz** [ChimeraTK/DeviceAccess-DoocsBackend#20]
This issue is related to the implementation of Register catalogue cache. 
[(https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/issues/6)]
Scenario. 
Server starts up with a local cache file. The caching mechanism runs in background and collects the properties. If a device (location) is offline the properties will not be cached. When caching is done, it will overwrite the original cache file and the properties from the offline locations will be lost.

**Comment by vargheseg** [comment]
7291dfbb50123ae8ae4a6585ba3a5c41f2b321e2 should address this bug
