### ISSUE TITLE
Proper implementation of isFunctional()

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess-DoocsBackend#22]
The current implementation of `isFunctional()` just returns whether the backens is opened.
In case the remote server is not reachable this ends in a fluctuating error state in ApplicationCore.

Provide a proper implementation that uses a reference register to read from to verify that the connection is actually working.

* [ ] Add a field in the CDD to give a reference register
* [ ] In `isFunctional()`, check if you can read from the reference register
* [ ] Check if it is possible to deduce a default value (the watchdog does it, but knows the server location)

**Comment by mhier** [comment]
The current implementation switches to false also if an exception is reported via setException(). This should be just fine.
