### ISSUE TITLE
Obtain event id and time stamp attached to properties

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-DoocsBackend#23]
DOOCS allows to attach an event id (= macro pulse number) and a time stamp to all property values. A mechanism is required to obtain this information through the DoocsBackend.

To map this functionality into the DeviceAccess interface, the DoocsBackend needs to create additional registers for these variables. Per property each one additional register for the event id and one for the time stamp must be added. The new registers should have "/eventId" and "/timeStamp" appended to the original name of the register. The registers should be read only.

Create two accessors which extract the event id resp. the time stamp from the property, instead of the actual data. (To be clear: yes, the actual data is thrown away at this point.) This accessor should work for any property type and with both normal rpc calls and zeromq (i.e. without and with the `AccessMode::wait_for_new_data` flag). Since the `DoocsBackendRegisterAccessor` base class already does all the type-independent part until the `EqData` object has been obtained, there should not be much to do to fulfil this requirement.

Through the function `EqData::get_event_id()` a `doocs::EventId` object can be obtained, through the `EqData::get_timestamp()` a `doocs::Timestamp` object can be obtained. This data then has to be converted (numerically correct!) into the UserType - please use the `numericToUserType()` function for this.

Make sure the accessors are read only: any write() must throw a ChimeraTK::logic_error, and also isWriteable(), isReadable() and isReadOnly() must return the correct values. These functions need to be overridden for this (they are currently incorrectly implemented anyway!).

Modify `DoocsBackend::getRegisterAccessor_impl()` to detect the suffixes and return the new respective accessor.

The new registers should also be added to the catalogue. Make sure all meta data for these registers is correct.

Write tests. You will need to extend the DoocsDummyServer to set proper time stamps and event ids.

Note: Don't worry that it is not possible to obtain the event id or time stamp consistently with the actual property value, because the accessors are separately reading the property. This will be fixed with separate tickets. You may need to keep this fact in mind though while writing the tests.

DoD:

- [x] Implement accessors (start with event id - the other one can also be done later in a separate ticket)
- [x] Modify backend itself to return accessors and change catalogue (catalogue change is also not so important at first and might be done later in a separate ticket)
- [x] Write tests
- [ ] Add documentation (Features section of mainpage)

**Comment by phako** [comment]
Is there a way to check if a doocs property is read-only without actually writing to it?

**Comment by phako** [comment]
Second question: How to handle the IFFF case? Should there be a eventId and timestamp for each of the subproperties?

**Comment by mhier** [comment]
> Is there a way to check if a doocs property is read-only without actually writing to it?

Why is this important in this case?


> Second question: How to handle the IFFF case? Should there be a eventId and timestamp for each of the subproperties?

I think there should be only one eventId and timestamp for the entire property.

**Comment by phako** [comment]
> > Is there a way to check if a doocs property is read-only without actually writing to it?
> 
> Why is this important in this case?

Because I mis-read the ticket to be about fixing that as well. So not at all.

**Comment by phako** [comment]
Works in principle, the tests break because they modify the timestamp

**Comment by phako** [comment]
I implemented the timestamp as int64 carrying the seconds since epoch (1.1.1970) is that enough or do we need higher precision?

**Comment by mhier** [comment]
I think that's what DOOCS internally also uses.

**Comment by phako** [comment]
the test for the eventId keeps failing in jenkins

**Comment by phako** [comment]
That is actually an issue with the latest commit in doocs-serverlib. Going back to 20.0.3 makes the test pass again.
