### ISSUE TITLE
Compatibility with DataConsistencyGroup

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-DoocsBackend#24]
The DataConsistencyGroup allows to get a consistent set of values from a group of accessors. It works for push-type transfers only (`AccessMode::wait_for_new_data` flag is set). The consistency check is based on the `ChimeraTK::VersionNumber`.

DOOCS offers a mechanism to check the consistency of a set of properties to some extend as well. This can be achieved by requiring the event id to match. This mechanism should be mapped onto the DeviceAccess functionality.

It is assumed that the DOOCS event id is monotonic. Each event id can then be mapped onto each one unique `ChimeraTK::VersionNumber`. When the DoocsBackend receives a value for a property, it needs to find the right  `ChimeraTK::VersionNumber` for the event id attached to the property and set its current  `ChimeraTK::VersionNumber` accordingly.

The mapping between  `ChimeraTK::VersionNumber` and DOOCS event id should be done on a per-process level, because the event id is synchronised even across different frontend servers through the timing system. Hence multiple DoocsBackends receiving data from different frontend servers should share the mapping, to allow a consistency check even across frontend servers.

Add a new class `DoocsBackend::EventIdMapper` with a single, static instance. The class should contain a `std::map<doocs::EventId, ChimeraTK::VersionNumber>` with a corresponding mutex to govern the access. Both should be private and the access should be realised through member functions, to prevent accidental misuse.

Mainly one member function of the `EventIdMapper` class is required: `EventIdMapper::getVersionForEventId()` takes a `doocs::EventId` as an argument. If the event id is found in the map, the corresponding `ChimeraTK::VersionNumber` is returned. Otherwise a new version number is returned (-> default constructor). This part can be made very simple at first (lock_guard + [] operator for the map, which automatically default-constructs if not yet present). Once everything works (or in a separate ticket) a "fast path" for the case that the event id is found should be added (test presence under read-lock, add new value under write-lock).

The `VersionNumber` is set in `DoocsBackendRegisterAccessor::doPostRead()`. Currently it is simply default-constructed (i.e. a new version is obtained). Instead, now the new function should be used. The event id can be obtained from the `DoocsBackendRegisterAccessorBase::dst` element.

Write a unit test checking the right behaviour of the VersionNumber of the read data. (Please do *not* unit-test internal interfaces like the  `DoocsBackend::EventIdMapper`)

DoD:
- [x] Implement `DoocsBackend::EventIdMapper`
- [x] Change `DoocsBackendRegisterAccessor::doPostRead()`
- [x] Write test
- [x] Add documentation (section "Features" in mainpage)

**Comment by phako** [comment]
Not exactly sure how I should test the "Hence multiple DoocsBackends receiving data from different frontend servers should share the mapping" part. I suppose I would need to instanciate a second DOOCS test server for that?

**Comment by mhier** [comment]
You need two different instances of the DoocsBackend for that. You can also achieve that by accessing the same test server through different CDDs (so the backend factory gives you a new instance). I guess that should be sufficient.

**Comment by phako** [comment]
Not sure if f451f27b24e427d19090d8624f74e8f37a8e7815 is good. It doesn't feel right

**Comment by phako** [comment]
Thinking about the fast path: I think the naïve implementation is sufficient and clear. Wouldn't you have to hold the read lock all the way down, even during inserting? Otherwise you could end up with:

Thread a takes the read lock, thread b tries to take the read lock.
Thread a finds eventId 1234 is not in the map, takes the write lock, releases the read lock
Thread b takes the read lock, checks the map, sees the eventId 1234 is not in the map, tries to take the write lock
Thread a adds the entry into the map, releases write lock
Thread b adds the entry into the map, overwrites Thread a's entry.

**Comment by mhier** [comment]
> Not sure if [f451f27](https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/commit/f451f27b24e427d19090d8624f74e8f37a8e7815) is good. It doesn't feel right

Can you elaborate?


> Thinking about the fast path: I think the naïve implementation is sufficient and clear. Wouldn't you have to hold the read lock all the way down, even during inserting? Otherwise you could end up with:

Maybe the terminology was unclear. This is one single shared_mutex. Read lock => lock shared, write lock => lock exclusive. While holding the exclusive lock, nobody can get the shared lock. 

Question: can one escalate a shared lock into an exclusive lock? If not, one has to release the shared lock and obtain the lock exclusively again, but in the mean time someone else might have changed the map already. So the test has to be repeated under exclusive lock then before inserting.

**Comment by phako** [comment]
> > Not sure if [f451f27](https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/commit/f451f27b24e427d19090d8624f74e8f37a8e7815) is good. It doesn't feel right
> 
> Can you elaborate?

It's just adapting the test to the new behavior, and I'm not sure if the correct way would be to update the dummy server to attach an increasing mpnum to all data (or set a global event id for doocs master) but that also seems way to overcomplex.

> 
> > Thinking about the fast path: I think the naïve implementation is sufficient and clear. Wouldn't you have to hold the read lock all the way down, even during inserting? Otherwise you could end up with:
> 
> Maybe the terminology was unclear. This is one single shared_mutex. Read lock => lock shared, write lock => lock exclusive. While holding the exclusive lock, nobody can get the shared lock.
> 
> Question: can one escalate a shared lock into an exclusive lock? If not, one has to release the shared lock and obtain the lock exclusively again, but in the mean time someone else might have changed the map already. So the test has to be repeated under exclusive lock then before inserting.

Upgradable locks did not make it into the spec, apparently (https://stackoverflow.com/questions/24334735/can-a-shared-lock-on-a-stdshared-timed-mutex-be-upgraded-to-an-exclusive-lock), but boost has them: https://www.boost.org/doc/libs/1_58_0/doc/html/thread/synchronization.html#thread.synchronization.mutex_concepts.upgrade_lockable.

Nevertheless, that should be a follow-up ticket then

**Comment by mhier** [comment]
> It's just adapting the test to the new behavior, and I'm not sure if the correct way would be to update the dummy server to attach an increasing mpnum to all data (or set a global event id for doocs master) but that also seems way to overcomplex.

I don't think that really matters for that test, as long as it is tested somewhere else that increasing the mpnum does the right thing. The behavior did change, so it is ok to change the test.

> Nevertheless, that should be a follow-up ticket then

Agreed.
