### ISSUE TITLE
Adapt to changes in DeviceAccess

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess-DoocsBackend#27]
Child of ChimeraTK/ApplicationCore#123
Depends on ChimeraTK/DeviceAccess#117, ChimeraTK/DeviceAccess#116 and ChimeraTK/DeviceAccess#119

Adapt to the changes in DeviceAccess:

*    ChimeraTK/DeviceAccess#116 and ChimeraTK/DeviceAccess#119 introduce API-breaking changes to pre/postRead/Write. Add the new arguments to the function overloads. Check Whether the functions should be used (for instance don't generate a new version number in postRead if readTransferLatest did not get new data)
*    ChimeraTK/DeviceAccess#117 introduces readTransfer() etc (non-overloaded functions without "do"). Use them whenever delegating or using a transfer (applies for all 6 read and write transfer functions)

**Comment by mhier** [comment]
Note: I have written a UnifiedBackendTest class in DeviceAccess (in tests/include resp. tests/src), which tests the correct behaviour of an accessor implementation w.r.t. exception handling. The test is reusable for different backends. It might be a good idea to use this test.
