### ISSUE TITLE
Some properties of location not included in generated cache file

### ISSUE THREAD

**Issue by ckampm** [ChimeraTK/DeviceAccess-DoocsBackend#31]
I have a setup where some properties of a location are not included in the generated cache file. This happens when the location is online and the missing properties can be read otherwise, e.g. using `doocsget` or with a manually written cache file.

The cache files generated on consecutive runs match, so this does not look like a corruption issue. It's also similar properties that are included or not:
```
  <register>
    <name>/Controller.PulseShape.delay</name>
    <length>1</length>
    <access_mode></access_mode>
    <doocs_type_id>6</doocs_type_id>
    <!--doocs id: DOUBLE-->
  </register>
```
can be read if included in the manually written cache file, while
```
  <register>
    <name>/Controller.FeedBack.Gain.Scheduling.stopTime</name>
    <length>1</length>
    <access_mode></access_mode>
    <doocs_type_id>6</doocs_type_id>
    <!--doocs id: DOUBLE-->
  </register>
```
shows up in the generated one.

The manually written and  generated files are attached (txt appended so Github accepts them):

[CK_162_5.cache.manual.txt](https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/files/4750823/CK_162_5.cache.manual.txt)

[CK_162_5.cache.txt](https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/files/4750820/CK_162_5.cache.txt)

**Comment by jhktimm** [comment]
DOOCS Problem, you can not have more than 4000 names.
`EqAdr ea;
EqCall eq;
EqData propList;
eq.names(&ea, &propList);`
propList.array_length() is not longer than 4000.
That is why you can not see some channels with rpc_test or with the CatalogueFetcher::fillCatalogue, but you can still see it with doogsget for example.
`doocsget -c doocs://localhost:610498009/F/D/CK_162_5/Controller.PulseShape.delay
`
So the workaround is still a manual <name>.cache file, set to read only.

**Comment by mhier** [comment]
Alternative work around: Split the one big location into multiple smaller ones (even though this is not really DOOCSish).

I think we can then close this ticket?
