### ISSUE TITLE
Potential deadlock in test_B_9_1/

### ISSUE THREAD

**Issue by phako** [ChimeraTK/DeviceAccess-DoocsBackend#33]
... asynchronous read
    registerName = MYDUMMY/SOME_ZMQINT

has the potential to deadlock; triggers especially well if run in tsan build

potentially between setException and deactivateAllAndPushException

**Comment by phako** [comment]
That is actually a side-effect of #32 and boost test catching the abort and then not being able to join the thread properly

**Comment by killenb** [comment]
We are currently reviewing if a workaround for a race condition in Dooocs zmq is functional.

**Comment by killenb** [comment]
As the condition variable what resolves the race condition is notified from all callbacks (also those with error notifications) there should be no blocking condition.
I necessary we can introduce a shutdown() function which notifies the condition variable later.
