### ISSUE TITLE
unified backend test B_8_5 fails

### ISSUE THREAD

**Issue by phako** [ChimeraTK/DeviceAccess-DoocsBackend#34]
`/usr/include/ChimeraTK/UnifiedBackendTest.h(1580): error in "unifiedBackendTest": check reg.readNonBlocking() == false failed`

The test creates an accessor before the device is opened. According to spec, there should be no asynchronous data transfer happening. 

The test shows that the first readNonBlocking() indirectly triggers asynchronous transfers for at least that accessor. This should not happen, only a dedicated call to `Device::activateAsyncRead()` should start asynchronous transfers

**Comment by killenb** [comment]
It turned out that the implementation was unnecessarily complicated due to an unnecessary requirement in the specification. The specification has been simplified (v01RC12), and the UnifiedBackendTest and the Doocs backend have been modified accordingly. Now all tests are passing.
