### ISSUE TITLE
EventIdMapper has intrinsic memory leak and performance issue

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-DoocsBackend#36]
It should throw out old entries after a while, but currently it does no such thing. Hence it will accumulate entries in the map with a frequency of e.g. 10 Hz, which presents a memory leak effectively (although data is still reachable and hence the sanitizer wouldn't find this).

Also performance will suffer if the map grows bigger, since the lookup tales longer.

There should be a maximum depth defined (possible hard-coded, make it quite large, like 1000 entries). If the size of the map exceeds the limit, find the entry with the smallest evenId and delete it. Since the map is ordered by its key, simply the first entry found via begin() can be deleted.

**Comment by nshehz** [comment]
commit ca80b65ed02564f8cafb32be0ee0defb806ba41a. Only indroduced a cap of max 2000 entries. For additional improvements circular buffer can be added. See TS for further checks to be added in relation to the addition and deletion of EventId into the map.
