### ISSUE TITLE
Analysis jobs take very long and get stuck

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess-DoocsBackend#37]
The time for a successful analysis job  has increased from 3 minutes to 25 minutes.
Sometimes jobs do not finish within 1h30 and are terminated. The TSAN job is always terminated

**Comment by phako** [comment]
Probably related to #38 which seems to cause a deadlock

**Comment by killenb** [comment]
The analysis jobs still take half an hour. Only the blocking is resolved.

**Comment by phako** [comment]
I'm not sure if we can speed it up. The unified backend test is taking long even without instrumentation, and asan/tsan don't exactly speed up things

**Comment by killenb** [comment]
Ah, I did not realise that this is due to the unified backend test, which is new. I guess that explains it. The info was not in this ticket.
