### ISSUE TITLE
Accessors can cause backwards counting event numbers

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess-DoocsBackend#45]
There currently are two conditions in which backwards counting event numbers can happen:

1. EventID *a* ist added to the EventIdMapper before EventID *a-1* because it arrives from another server or another variable.
A variable is seeing both EventID *a-1* and *a*.
2. A device has seen an exception, which causes the ApplicationCore ExceptionHandlingDecorator to attach the DeviceModule exceptionVersion. When the device comes back online, the data is still unchanged and in the map. The EventIdMapper returns the mapped version number, which in the DoocsBackend accessor is equal to the previous one, and sends it. In the decorated accessor the version is decreasing.

Solutions for both cases are in the specificaton https://chimeratk.github.io/DeviceAccess-DoocsBackend/master/spec__doocs_backend.html. (1. is done in B.1.1.3.1, 2. is done in B.1.2 and B.1.3.3.1)

**Comment by mhier** [comment]
2.) has been solved.
