### ISSUE TITLE
CMake file boken for debug configuration

### ISSUE THREAD

**Issue by zenker** [ChimeraTK/DeviceAccess-DoocsBackend#56]
In https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/blob/a759cfbbd02d8c912601582c65af4ecac0009c5c/CMakeLists.txt#L68 `Makefile.coverage.in` needs to be replaced by `make_coverage.sh.in`.

**Comment by mhier** [comment]
thanks, fixed.
