### ISSUE TITLE
Register catalogue cache

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/DeviceAccess-DoocsBackend#6]
Filling the catalogue for DOOCS backends can take a very long time, since DOOCS register enumeration is very slow. Add persistent caching functionality for register catalogue to speed this up.

This should work as follows:

When the device is opened:
* Check for presence of cache file. If existent, fill catalogue with its content
* In any case, launch a new thread which obtains/refreshes the catalogue in the background
* When the catalogue filling in background finishes, write the cache file

This behaviour should be configurable through the CDD. By default it should be turned off. If a CDD parameter called 'cache' exists, it will be turned on. The value of the parameter will be the name of the cache file.

Definition of done:
- [x] Implementation
- [ ] Tests (3 main cases: feature turned off, feature enabled but cache file missing, feature enabled and cache file exists; in addition exception handling: file unreadable, file unwritable, file corrupted -> logic_error)
- [ ] User documentation incl. CDD syntax

**Comment by mhier** [comment]
There is a second use-case for the cache besides speeding up: If an ApplicationCore-based server requires some information from another server (e.g. trigger from x2timer), the presence of a cache file can allow the server to start even when the other server is currently offline (the new exception handling would jump in immediately and retry contacting the server until it is reachable). For this purpose it is very useful if the cache file is plain text, so it can be provided with the server resp. configuration tool. Also things would be easier, if the cache file only contains the part of the property name which is not mentioned in the CDD (i.e. in the dmap file), so the same cache file can be used for different instances of the server.

**Comment by vargheseg** [comment]
pending tasks tracked by:
https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/issues/12

**Comment by mhier** [comment]
Sorry but the current implementation is not sufficient. There is one requirement which is missing in the ticket description (sorry about that): We need to obtain register accessors even if the device cannot be opened. The information in the cache is not sufficient for this. We need to store the original DOOCS data type somewhere to decide which accessor to return. This information is not available in the public catalogue, hence it will not be cached right now.

**Comment by mhier** [comment]
I think it's rather straight forward. We can just add the original DOOCS type to the catalogue entry. I will quickly do it.

**Comment by mhier** [comment]
now it seems to work.

**Comment by mhier** [comment]
Sorry, I have to reopen this once more. The backend should update the cache file even if it already exists. Also it should always write out the cache file when it finished filling the catalogue, not only when the catalogue is requested by the application (as long as caching is enabled of course).

**Comment by vargheseg** [comment]
https://github.com/ChimeraTK/DeviceAccess-DoocsBackend/commit/bfd2499684df49c8cdb6d51b04f1a1c80493ceb6 should provide required behavior

**Comment by mhier** [comment]
When writing the cache file by hand, there is now a very unintuitive behaviour for IFFF. The entry for the I component in the cache file will create all 4 register entries in the catalogue, while the other 3 have no effect. If one only creates e.g. one of the F components, no register will be added to the catalogue. I think it would be better to change this.

This can be done even in a way that no special handling is necessary any more: At the end of parseRegister() you now have a list of registers. Just keep only the one entry from the list which is defined by the node. To strip the extra "/I" etc. at the end, just search for a 4th slash in the property name - that part is not the DOOCS property name but the component of the property. This is the logic which is used else in the backend to handle similar decisions.

**Comment by mhier** [comment]
Another question: Why do you write out the cache file only when destroying the backend or when requesting the catalogue? Wouldn't it be easier to do that in the single point where the catalogue filling is complete? This would also help testing this feature: right now I have no way to know when filling the catalogue is done (it takes maybe 10th of minutes), hence I do not know when to stop the server to observe whether the cache file has been updated.

**Comment by vargheseg** [comment]
Agreed. Behavior changed as suggested.

**Comment by mhier** [comment]
It seems to work now. Thanks!
